#
# Copyright (C) 2023 The Android Open Source Project
# Copyright (C) 2023 SebaUbuntu's TWRP device tree generator
#
# SPDX-License-Identifier: Apache-2.0
#

DEVICE_PATH := device/samsung/a02

# For building with minimal manifest
ALLOW_MISSING_DEPENDENCIES := true

# Architecture
TARGET_ARCH := arm
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_CPU_VARIANT := generic
TARGET_CPU_VARIANT_RUNTIME := cortex-a53

BOARD_VENDOR := samsung
TARGET_SOC := k39tv1_bsp_titan_hamster
TARGET_BOOTLOADER_BOARD_NAME := k39tv1_bsp_titan_hamster
TARGET_BOARD_PLATFORM := mt6739
TARGET_BOARD_PLATFORM_GPU := powervr

TARGET_USES_64_BIT_BINDER := true

# Kernel
BOARD_KERNEL_BASE := 0x40000000
BOARD_KERNEL_PAGESIZE := 2048
TARGET_PREBUILT_KERNEL := $(DEVICE_PATH)/prebuilt/Image
BOARD_KERNEL_CMDLINE := androidboot.hardware=mt6739
BOARD_MKBOOTIMG_ARGS := --kernel_offset 0x00008000 --ramdisk_offset 0x05000000 --tags_offset 0x04000000 --header_version 2 --board SRPTK19C000SA

# Partitions
BOARD_FLASH_BLOCK_SIZE := 131072
BOARD_BOOTIMAGE_PARTITION_SIZE := 25165824
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 25165824
BOARD_HAS_LARGE_FILESYSTEM := true
BOARD_SYSTEMIMAGE_PARTITION_TYPE := ext4
BOARD_USERDATAIMAGE_FILE_SYSTEM_TYPE := f2fs
BOARD_VENDORIMAGE_FILE_SYSTEM_TYPE := ext4
TARGET_COPY_OUT_VENDOR := vendor

# Dynamic Partitions
BOARD_SAMSUNG_DYNAMIC_PARTITIONS_PARTITION_LIST := system vendor product odm
BOARD_SAMSUNG_DYNAMIC_PARTITIONS_SIZE := 4068474880

# Recovery
BOARD_INCLUDE_RECOVERY_DTBO := true
TARGET_USERIMAGES_USE_EXT4 := true

# Security patch level
VENDOR_SECURITY_PATCH := 2021-08-01

# Verified Boot
BOARD_AVB_ENABLE := false

# --- ORANGEFOX CONFIGURATIONS ---
# FOX_VERSION := R11.1
# FOX_BUILD_TYPE := Unofficially
# FOX_USE_TWRP_RECOVERY_IMAGE_BUILDER := 1
# TARGET_DEVICE_ALT := a02, SM-A022F, a022

# Diet Ketat untuk Partisi 24MB
# FOX_LANGUAGES := "en"
# FOX_REMOVE_AROMA_LS := 1
# FOX_NO_SAMSUNG_SPECIAL := 1
# FOX_USE_RECOVERY_FLASHLIGHT := 0
# FOX_EXCLUDE_NANO := 1
# FOX_EXCLUDE_BASH := 1
# FOX_USE_SPECIFIC_MAGISK_ZIP := ""

# Tambahan Diet Ekstra Biar Crypto Muat
# FOX_DELETE_MAGISK_ADDON := 1
# FOX_REMOVE_BASH := 1
# FOX_EXCLUDE_TAR := 1

# Kompresi & Display
LZMA_RAMDISK_TARGET := true
TARGET_SCREEN_WIDTH := 720
TARGET_SCREEN_HEIGHT := 1600
TARGET_RECOVERY_PIXEL_FORMAT := "BGRA_8888"

# TWRP & Storage Flags
RECOVERY_SDCARD_ON_DATA := true
TW_THEME := portrait_hdpi
TW_BRIGHTNESS_PATH := "/sys/class/backlight/panel/brightness"
TW_MAX_BRIGHTNESS := 255
TW_DEFAULT_BRIGHTNESS := 100
TW_Y_OFFSET := 84
TW_H_OFFSET := -84
TW_EXCLUDE_TZDATA := true
TW_EXCLUDE_LPDUMP := true
TW_HAS_DOWNLOAD_MODE := true
TW_EXCLUDE_DEFAULT_USB_INIT := true
TW_INTERNAL_STORAGE_PATH := "/data/media/0"
TW_INTERNAL_STORAGE_MOUNT_POINT := "data"
TW_EXTERNAL_STORAGE_PATH := "/external_sd"
TW_EXTERNAL_STORAGE_MOUNT_POINT := "external_sd"
TW_NO_LEGACY_PROPS := true
TW_NO_BIND_SYSTEM := true
TW_INCLUDE_CRYPTO := true
TW_INCLUDE_CRYPTO_FBE := true
TW_INCLUDE_FBE_METADATA_DECRYPT := true
TW_EXCLUDE_APEX := true
TW_EXCLUDE_PYTHON := true
TW_EXCLUDE_NANO := true
TW_EXCLUDE_TWRPAPP := true
BOARD_USES_METADATA_ENCRYPTION := true
TW_INPUT_BLACKLIST := "hbtp_vm"
TW_SUPPORT_INPUT_1_2 := true
TW_FILTER_TOUCH_EVENTS := true
TW_EVENT_LOGGING := false
